### ISSUE TITLE
Make sure installation works with a clean distribution that can be refreshed by non-devs

### ISSUE THREAD

**Issue by jamieaa64** [FreelyGive/contacts#17]
**Why are we doing this?**  The purpose is

- Our distribution needs to install cleanly (We currently using Simplytest me as a means to test if it is something that can install cleanly)
- To make it easier for non-devs to test things quickly 

**Notes**
- It would be nice but less important: To make it easier for people outside of the contacts community to get a demo fast without having to talk to anyone. 
- Therefore if we don't do this we need to create dev sites that we need to refresh
- we also need some way to do QA but will probably not solve it here

**Timebox:**  Spent up to half an hour on this

- [ ] Figure out why the modules aren't enabled sometimes
- [ ] Figure out why Drupal 8 core patches aren't bought across

If this fails
- [ ] Create dev environments that non-devs can refresh

**Comment by andrewbelcher** [comment]
We can install on [simplytest.me](https://simplytest.me/project/contacts_kickstart/8.x-1.x)!
